version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: npm
    versions:
    - 6.14.11
    - 7.10.0
    - 7.11.0
    - 7.5.3
    - 7.5.4
    - 7.5.6
    - 7.6.0
    - 7.6.1
    - 7.6.2
    - 7.6.3
    - 7.7.0
    - 7.7.4
    - 7.7.5
    - 7.7.6
    - 7.8.0
    - 7.9.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: react-bootstrap
    versions:
    - 1.3.0
    - 1.5.0
    - 1.5.1
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.1.4
    - 3.3.1
  - dependency-name: react-slick
    versions:
    - 0.28.0
  - dependency-name: react-highlight
    versions:
    - 0.13.0
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: bootstrap
    versions:
    - 4.5.0
  - dependency-name: jquery
    versions:
    - 3.5.1
